version: "3.9"

services:
  rodofbot:
    build:
      context: .
      target: dev
    image: rodofbot:dev
    container_name: rodofbot
    volumes:
      - ./src:/app/src  # live reloadable code
    environment:
      - .env
    depends_on:
      - pgvector
    command: ["python", "-m", "src.bot"]

  pgvector:
    image: pgvector/pgvector
    container_name: pgvector
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${VECTOR_STORE__DBNAME}
      POSTGRES_USER: ${VECTOR_STORE__USER}
      POSTGRES_PASSWORD: ${VECTOR_STORE__PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
