version: "3.9"

services:
  smartquotebot:
    image: thomas934/smartquotebot:latest  # <-- lowercase repo name (Docker Hub requires lowercase!)
    container_name: smartquotebot
    environment:
      # Bot config
      - BOT__TOKEN=${BOT__TOKEN}
      - BOT__COMMAND_PREFIX=${BOT__COMMAND_PREFIX}

      # Sentry
      - SENTRY__ENABLE=${SENTRY__ENABLE}
      - SENTRY__DSN=${SENTRY__DSN}
      - SENTRY__SEND_PII=${SENTRY__SEND_PII}
      - SENTRY__TRACES_SAMPLE_RATE=${SENTRY__TRACES_SAMPLE_RATE}
      - SENTRY__PROFILING_SAMPLE_RATE=${SENTRY__PROFILING_SAMPLE_RATE}

      # Paths
      - PATHS__DATA_DIR=${PATHS__DATA_DIR}
      - PATHS__LOGS_DIR=${PATHS__LOGS_DIR}
      - PATHS__QUOTES_FILE=${PATHS__QUOTES_FILE}
      - PATHS__QUOTES_INDEX_FILE=${PATHS__QUOTES_INDEX_FILE}

      # AI
      - AI__EMBEDDING_MODEL=${AI__EMBEDDING_MODEL}

    depends_on:
      - pgvector-db
    restart: unless-stopped
    networks:
      - rodofbot-network

  pgvector-db:
    image: pgvector/pgvector:latest
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vectorstore
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - rodofbot-network

networks:
  rodofbot-network:
    driver: bridge
