version: "3.9"

services:
  rodofbot:
    build:
      context: .
      target: dev
    image: rodofbot:dev
    volumes:
      - ./src:/app/src

    environment:
      # --- Bot Settings ---
      - BOT__TOKEN=${BOT__TOKEN}
      - BOT__COMMAND_PREFIX=${BOT__COMMAND_PREFIX}

      # --- Sentry Settings ---
      - SENTRY__ENABLE=${SENTRY__ENABLE}
      - SENTRY__DSN=${SENTRY__DSN}
      - SENTRY__SEND_PII=${SENTRY__SEND_PII}
      - SENTRY__TRACES_SAMPLE_RATE=${SENTRY__TRACES_SAMPLE_RATE}
      - SENTRY__PROFILING_SAMPLE_RATE=${SENTRY__PROFILING_SAMPLE_RATE}

      # --- Vector Store Service Config ---
      - VECTOR_STORE_SERVICE__DB_URL=${VECTOR_STORE_SERVICE__DB_URL}
      - VECTOR_STORE_SERVICE__EMBEDDING_MODEL=${VECTOR_STORE_SERVICE__EMBEDDING_MODEL}
      - VECTOR_STORE_SERVICE__EMBEDDING_DIMENSION=${VECTOR_STORE_SERVICE__EMBEDDING_DIMENSION}

    command: ["python", "-m", "src.bot"]
