# .github/workflows/build-dev.yml

name: Build & Push Dev Image (GHCR)

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Architecture (amd64, arm64, or both)'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - arm64
          - both

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine platforms
        id: arch
        run: |
          if [[ "${{ github.event.inputs.architecture }}" == "both" ]]; then
            echo "platforms=linux/amd64,linux/arm64" >> "$GITHUB_OUTPUT"
            echo "suffix=multiarch" >> "$GITHUB_OUTPUT"
          else
            echo "platforms=linux/${{ github.event.inputs.architecture }}" >> "$GITHUB_OUTPUT"
            echo "suffix=${{ github.event.inputs.architecture }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dev image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ steps.arch.outputs.platforms }}
          target: dev
          tags: ghcr.io/thomas934/smart-quote-bot:dev-${{ steps.arch.outputs.suffix }}
